<?php

namespace Database\Seeders;

use App\Models\Oil;
use Illuminate\Database\Seeder;

class OilSeeder extends Seeder
{
    public function run(): void
    {
        $oils = [
            ['code' => 'OIL-001', 'name' => ['en' => 'Lavender Essential Oil', 'tr' => 'Lavanta Esansiyel Yağı', 'ar' => 'زيت اللافندر الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Aura Cacia', 'volume' => 30, 'price' => 12.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Pure lavender essential oil for relaxation', 'tr' => 'Rahatlama için saf lavanta esansiyel yağı', 'ar' => 'زيت اللافندر الأساسي النقي للاسترخاء'], 'supplier' => 'Nature\'s Gift'],
            ['code' => 'OIL-002', 'name' => ['en' => 'Peppermint Essential Oil', 'tr' => 'Nane Esansiyel Yağı', 'ar' => 'زيت النعناع الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Now Foods', 'volume' => 30, 'price' => 9.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Cooling and refreshing peppermint oil', 'tr' => 'Ferahlatıcı nane yağı', 'ar' => 'زيت النعناع المنعش والبارد'], 'supplier' => 'Nature\'s Gift'],
            ['code' => 'OIL-003', 'name' => ['en' => 'Tea Tree Essential Oil', 'tr' => 'Çay Ağacı Esansiyel Yağı', 'ar' => 'زيت شجرة الشاي الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Thursday Plantation', 'volume' => 25, 'price' => 14.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Antimicrobial tea tree oil', 'tr' => 'Antimikrobiyal çay ağacı yağı', 'ar' => 'زيت شجرة الشاي المضاد للميكروبات'], 'supplier' => 'Essential Oils Ltd'],
            ['code' => 'OIL-004', 'name' => ['en' => 'Eucalyptus Essential Oil', 'tr' => 'Okaliptüs Esansiyel Yağı', 'ar' => 'زيت الأوكالبتوس الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Aura Cacia', 'volume' => 30, 'price' => 11.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Clear breathing eucalyptus oil', 'tr' => 'Nefes açıcı okaliptüs yağı', 'ar' => 'زيت الأوكالبتوس المنعش للتنفس'], 'supplier' => 'Nature\'s Gift'],
            ['code' => 'OIL-005', 'name' => ['en' => 'Rose Absolute Fragrance Oil', 'tr' => 'Gül Mutlak Koku Yağı', 'ar' => 'زيت عطر الورد المطلق'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'Eden Botanicals', 'volume' => 15, 'price' => 34.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Rich Bulgarian rose fragrance', 'tr' => 'Zengin Bulgar gülü kokusu', 'ar' => 'رائحة الورد البلغاري الغنية'], 'supplier' => 'Eden Botanicals'],
            ['code' => 'OIL-006', 'name' => ['en' => 'Vanilla Fragrance Oil', 'tr' => 'Vanilya Koku Yağı', 'ar' => 'زيت عطر الفانيليا'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'CandleScience', 'volume' => 100, 'price' => 15.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Sweet warm vanilla fragrance', 'tr' => 'Tatlı sıcak vanilya kokusu', 'ar' => 'رائحة الفانيليا الحلوة الدافئة'], 'supplier' => 'CandleScience'],
            ['code' => 'OIL-007', 'name' => ['en' => 'Sandalwood Fragrance Oil', 'tr' => 'Sandal Ağacı Koku Yağı', 'ar' => 'زيت عطر الصندل'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'Eden Botanicals', 'volume' => 30, 'price' => 28.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Creamy woody sandalwood', 'tr' => 'Kremamsı odunsu sandal ağacı', 'ar' => 'صندل كريمي خشبي'], 'supplier' => 'Eden Botanicals'],
            ['code' => 'OIL-008', 'name' => ['en' => 'Oud Fragrance Oil', 'tr' => 'Ud Koku Yağı', 'ar' => 'زيت عطر العود'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'Eden Botanicals', 'volume' => 15, 'price' => 45.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Rich dark agarwood fragrance', 'tr' => 'Zengin koyu ud kokusu', 'ar' => 'رائحة العود الداكنة الغنية'], 'supplier' => 'Eden Botanicals'],
            ['code' => 'OIL-009', 'name' => ['en' => 'Jojoba Carrier Oil', 'tr' => 'Jojoba Taşıyıcı Yağı', 'ar' => 'زيت الجوجوبا الناقل'], 'category' => ['en' => 'Carrier Oil', 'tr' => 'Taşıyıcı Yağ', 'ar' => 'زيت ناقل'], 'brand' => 'Now Foods', 'volume' => 250, 'price' => 18.99, 'shelf' => 'Shelf 03', 'section' => 'Section C', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Cold-pressed jojoba oil', 'tr' => 'Soğuk pres jojoba yağı', 'ar' => 'زيت الجوجوبا المعصور على البارد'], 'supplier' => 'Now Foods'],
            ['code' => 'OIL-010', 'name' => ['en' => 'Sweet Almond Carrier Oil', 'tr' => 'Tatlı Badem Taşıyıcı Yağı', 'ar' => 'زيت اللوز الحلو الناقل'], 'category' => ['en' => 'Carrier Oil', 'tr' => 'Taşıyıcı Yağ', 'ar' => 'زيت ناقل'], 'brand' => 'Aura Cacia', 'volume' => 250, 'price' => 14.99, 'shelf' => 'Shelf 03', 'section' => 'Section C', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Light moisturizing almond oil', 'tr' => 'Hafif nemlendirici badem yağı', 'ar' => 'زيت اللوز المرطب الخفيف'], 'supplier' => 'Nature\'s Gift'],
            ['code' => 'OIL-011', 'name' => ['en' => 'Coconut Carrier Oil', 'tr' => 'Hindistan Cevizi Taşıyıcı Yağı', 'ar' => 'زيت جوز الهند الناقل'], 'category' => ['en' => 'Carrier Oil', 'tr' => 'Taşıyıcı Yağ', 'ar' => 'زيت ناقل'], 'brand' => 'Now Foods', 'volume' => 500, 'price' => 22.99, 'shelf' => 'Shelf 03', 'section' => 'Section C', 'warehouse' => 'Warehouse 3', 'notes' => ['en' => 'Fractionated coconut oil', 'tr' => 'Fraksiyone hindistan cevizi yağı', 'ar' => 'زيت جوز الهند المجزأ'], 'supplier' => 'Now Foods'],
            ['code' => 'OIL-012', 'name' => ['en' => 'Grapeseed Carrier Oil', 'tr' => 'Üzüm Çekirdeği Taşıyıcı Yağı', 'ar' => 'زيت بذور العنب الناقل'], 'category' => ['en' => 'Carrier Oil', 'tr' => 'Taşıyıcı Yağ', 'ar' => 'زيت ناقل'], 'brand' => 'Aura Cacia', 'volume' => 500, 'price' => 16.99, 'shelf' => 'Shelf 03', 'section' => 'Section C', 'warehouse' => 'Warehouse 3', 'notes' => ['en' => 'Light non-greasy grapeseed oil', 'tr' => 'Hafif yağsız üzüm çekirdeği yağı', 'ar' => 'زيت بذور العنب الخفيف غير الدهني'], 'supplier' => 'Nature\'s Gift'],
            ['code' => 'OIL-013', 'name' => ['en' => 'Bergamot Essential Oil', 'tr' => 'Bergamot Esansiyel Yağı', 'ar' => 'زيت البرغموت الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Now Foods', 'volume' => 30, 'price' => 16.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Sunny citrus bergamot oil', 'tr' => 'Güneşli narenciye bergamot yağı', 'ar' => 'زيت البرغموت الحمضي المشمس'], 'supplier' => 'Essential Oils Ltd'],
            ['code' => 'OIL-014', 'name' => ['en' => 'Lemon Essential Oil', 'tr' => 'Limon Esansiyel Yağı', 'ar' => 'زيت الليمون الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Aura Cacia', 'volume' => 30, 'price' => 8.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 1', 'notes' => ['en' => 'Bright zesty lemon oil', 'tr' => 'Parlak limon yağı', 'ar' => 'زيت الليمون المنعش'], 'supplier' => 'Nature\'s Gift'],
            ['code' => 'OIL-015', 'name' => ['en' => 'Frankincense Essential Oil', 'tr' => 'Buhur Esansiyel Yağı', 'ar' => 'زيت اللبان الأساسي'], 'category' => ['en' => 'Essential Oil', 'tr' => 'Esansiyel Yağ', 'ar' => 'زيت عطري'], 'brand' => 'Eden Botanicals', 'volume' => 15, 'price' => 29.99, 'shelf' => 'Shelf 01', 'section' => 'Section A', 'warehouse' => 'Warehouse 3', 'notes' => ['en' => 'Premium frankincense sacra oil', 'tr' => 'Premium buhur yağı', 'ar' => 'زيت اللبان الممتاز'], 'supplier' => 'Eden Botanicals'],
            ['code' => 'OIL-016', 'name' => ['en' => 'Musk Fragrance Oil', 'tr' => 'Misk Koku Yağı', 'ar' => 'زيت عطر المسك'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'CandleScience', 'volume' => 100, 'price' => 18.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Clean white musk fragrance', 'tr' => 'Temiz beyaz misk kokusu', 'ar' => 'رائحة المسك الأبيض النظيفة'], 'supplier' => 'CandleScience'],
            ['code' => 'OIL-017', 'name' => ['en' => 'Amber Fragrance Oil', 'tr' => 'Amber Koku Yağı', 'ar' => 'زيت عطر العنبر'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'CandleScience', 'volume' => 100, 'price' => 16.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 2', 'notes' => ['en' => 'Warm amber fragrance oil', 'tr' => 'Sıcak amber koku yağı', 'ar' => 'زيت عطر العنبر الدافئ'], 'supplier' => 'CandleScience'],
            ['code' => 'OIL-018', 'name' => ['en' => 'Tobacco Fragrance Oil', 'tr' => 'Tütün Koku Yağı', 'ar' => 'زيت عطر التبغ'], 'category' => ['en' => 'Fragrance Oil', 'tr' => 'Koku Yağı', 'ar' => 'زيت عطر'], 'brand' => 'Eden Botanicals', 'volume' => 30, 'price' => 24.99, 'shelf' => 'Shelf 02', 'section' => 'Section B', 'warehouse' => 'Warehouse 3', 'notes' => ['en' => 'Rich tobacco leaf fragrance', 'tr' => 'Zengin tütün yaprağı kokusu', 'ar' => 'رائحة أوراق التبغ الغنية'], 'supplier' => 'Eden Botanicals'],
            ['code' => 'OIL-019', 'name' => ['en' => 'Vitamin E Carrier Oil', 'tr' => 'E Vitamini Taşıyıcı Yağı', 'ar' => 'زيت فيتامين E الناقل'], 'category' => ['en' => 'Carrier Oil', 'tr' => 'Taşıyıcı Yağ', 'ar' => 'زيت ناقل'], 'brand' => 'Now Foods', 'volume' => 120, 'price' => 19.99, 'shelf' => 'Shelf 03', 'section' => 'Section C', 'warehouse' => 'Warehouse 3', 'notes' => ['en' => 'Rich vitamin E oil', 'tr' => 'Zengin E vitamini yağı', 'ar' => 'زيت فيتامين E الغني'], 'supplier' => 'Now Foods'],
            ['code' => 'OIL-020', 'name' => ['en' => 'Argan Carrier Oil', 'tr' => 'Argan Taşıyıcı Yağı', 'ar' => 'زيت الأركان الناقل'], 'category' => ['en' => 'Carrier Oil', 'tr' => 'Taşıyıcı Yağ', 'ar' => 'زيت ناقل'], 'brand' => 'Aura Cacia', 'volume' => 120, 'price' => 24.99, 'shelf' => 'Shelf 03', 'section' => 'Section C', 'warehouse' => 'Warehouse 3', 'notes' => ['en' => 'Pure argan oil from Morocco', 'tr' => 'Fas\'tan saf argan yağı', 'ar' => 'زيت الأركان النقي من المغرب'], 'supplier' => 'Nature\'s Gift'],
        ];

        foreach ($oils as $oil) {
            Oil::create($oil);
        }
    }
}
