<?php

namespace Database\Seeders;

use App\Models\FragranceCategory;
use App\Models\Perfume;
use App\Models\Season;
use Illuminate\Database\Seeder;

class PerfumeSeeder extends Seeder
{
    public function run(): void
    {
        $perfumes = [
            ['code' => 'CR-001', 'name' => 'Creed Aventus', 'original_perfume' => 'Creed Aventus', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Summer', 'notes' => 'Smoky pineapple and birch', 'top_notes' => 'Pineapple, Bergamot, Apple', 'middle_notes' => 'Birch, Jasmine, Rose', 'base_notes' => 'Musk, Oakmoss, Ambergris', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 295.00],
            ['code' => 'CR-002', 'name' => 'Creed Silver Mountain Water', 'original_perfume' => 'Creed Silver Mountain Water', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Summer', 'notes' => 'Alpine freshness with black currant', 'top_notes' => 'Bergamot, Mandarin, Black Currant', 'middle_notes' => 'Green Tea, Galbanum', 'base_notes' => 'Musk, Sandalwood, Petigrain', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 285.00],
            ['code' => 'CR-003', 'name' => 'Creed Green Irish Tweed', 'original_perfume' => 'Creed Green Irish Tweed', 'gender' => 'Erkek', 'family' => 'Green', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Spring', 'notes' => 'Fresh green fields and lemon verbena', 'top_notes' => 'Lemon, Bergamot, Mint', 'middle_notes' => 'Green Leaves, Violet, Sandalwood', 'base_notes' => 'Ambergris, Musk, Cedar', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 280.00],
            ['code' => 'DX-001', 'name' => 'Dior Sauvage', 'original_perfume' => 'Dior Sauvage', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Summer', 'notes' => 'Spicy and fresh ambroxan', 'top_notes' => 'Bergamot, Pepper, Sichuan Pepper', 'middle_notes' => 'Lavender, Geranium, Elemi', 'base_notes' => 'Ambroxan, Cedar, Labdanum', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Toilette', 'sillage' => 'Heavy', 'price' => 135.00],
            ['code' => 'DX-002', 'name' => 'Dior Fahrenheit', 'original_perfume' => 'Dior Fahrenheit', 'gender' => 'Erkek', 'family' => 'Leather', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Winter', 'notes' => 'Bold leather with violet', 'top_notes' => 'Violet, Lavender, Nutmeg', 'middle_notes' => 'Leather, Jasmine, Honeysuckle', 'base_notes' => 'Leather, Vetiver, Amber', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 120.00],
            ['code' => 'DX-003', 'name' => 'Dior Homme Intense', 'original_perfume' => 'Dior Homme Intense', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Autumn', 'notes' => 'Warm iris and leather', 'top_notes' => 'Lavender, Sage, Coriander', 'middle_notes' => 'Iris, Pear, Cedar', 'base_notes' => 'Leather, Cedar, Amber', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 130.00],
            ['code' => 'TF-001', 'name' => 'Tom Ford Oud Wood', 'original_perfume' => 'Tom Ford Oud Wood', 'gender' => 'Erkek', 'family' => 'Woody', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Winter', 'notes' => 'Exotic oud with warm spices', 'top_notes' => 'Oud, Sandalwood, Cardamom', 'middle_notes' => 'Sandalwood, Rose, Cedar', 'base_notes' => 'Amber, Vanilla, Tonka', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 250.00],
            ['code' => 'TF-002', 'name' => 'Tom Ford Tobacco Vanille', 'original_perfume' => 'Tom Ford Tobacco Vanille', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Winter', 'notes' => 'Sweet tobacco and creamy vanilla', 'top_notes' => 'Tobacco Leaf, Vanilla, Cacao', 'middle_notes' => 'Tobacco, Vanilla, Tonka', 'base_notes' => 'Dried Fruits, Woody Notes', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 260.00],
            ['code' => 'TF-003', 'name' => 'Tom Ford Neroli Portofino', 'original_perfume' => 'Tom Ford Neroli Portofino', 'gender' => 'Unisex', 'family' => 'Citrus', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Summer', 'notes' => 'Bright citrus and floral', 'top_notes' => 'Neroli, Bergamot, Lemon', 'middle_notes' => 'Orange Blossom, Jasmine, Lavender', 'base_notes' => 'Amber, Musk, Angelica', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Soft', 'price' => 240.00],
            ['code' => 'BL-001', 'name' => 'Bleu de Chanel', 'original_perfume' => 'Bleu de Chanel', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Spring', 'notes' => 'Sophisticated citrus aromatic', 'top_notes' => 'Grapefruit, Lemon, Mint', 'middle_notes' => 'Ginger, Jasmine, Iso E Super', 'base_notes' => 'Cedar, Sandalwood, Amber', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 150.00],
            ['code' => 'CH-002', 'name' => 'Chanel No. 5', 'original_perfume' => 'Chanel No. 5', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Spring', 'notes' => 'Timeless floral aldehydic', 'top_notes' => 'Aldehydes, Bergamot, Lemon', 'middle_notes' => 'Jasmine, Rose, Iris', 'base_notes' => 'Vanilla, Amber, Sandalwood', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 175.00],
            ['code' => 'CH-003', 'name' => 'Chanel Coco Mademoiselle', 'original_perfume' => 'Chanel Coco Mademoiselle', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Spring', 'notes' => 'Modern oriental floral', 'top_notes' => 'Orange, Bergamot, Grapefruit', 'middle_notes' => 'Rose, Jasmine, Lychee', 'base_notes' => 'Musk, Vanilla, Patchouli', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 160.00],
            ['code' => 'YS-001', 'name' => 'Yves Saint Laurent La Nuit', 'original_perfume' => 'YSL La Nuit de L\'Homme', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 03', 'section' => 'Section A', 'season' => 'Autumn', 'notes' => 'Mysterious cardamom and lavender', 'top_notes' => 'Cardamom, Bergamot, Lavender', 'middle_notes' => 'Cedar, Sage, Coumarin', 'base_notes' => 'Vetiver, Leather, Caraway', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 110.00],
            ['code' => 'YS-002', 'name' => 'YSL Black Opium', 'original_perfume' => 'YSL Black Opium', 'gender' => 'Kadın', 'family' => 'Oriental', 'shelf' => 'Shelf 03', 'section' => 'Section A', 'season' => 'Winter', 'notes' => 'Addictive coffee and vanilla', 'top_notes' => 'Coffee, Pink Pepper, Orange Blossom', 'middle_notes' => 'Jasmine, Licorice, Almond', 'base_notes' => 'Vanilla, Patchouli, Cedar', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 125.00],
            ['code' => 'YS-003', 'name' => 'YSL Libre', 'original_perfume' => 'YSL Libre', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 03', 'section' => 'Section A', 'season' => 'Spring', 'notes' => 'Floral fougère with lavender', 'top_notes' => 'Lavender, Mandarin, Black Currant', 'middle_notes' => 'Lavender, Jasmine, Orange Blossom', 'base_notes' => 'Musk, Vanilla, Cedar', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 130.00],
            ['code' => 'JM-001', 'name' => 'Jo Malone London English Pear', 'original_perfume' => 'Jo Malone English Pear & Freesia', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 03', 'section' => 'Section B', 'season' => 'Autumn', 'notes' => 'Ripe pear and white freesia', 'top_notes' => 'Pear, Melon, Quince', 'middle_notes' => 'Freesia, Rose, Lily', 'base_notes' => 'Musk, Amber, Rhubarb', 'warehouse' => 'Warehouse 2', 'concentration' => 'Cologne', 'sillage' => 'Soft', 'price' => 85.00],
            ['code' => 'JM-002', 'name' => 'Jo Malone Wood Sage & Sea Salt', 'original_perfume' => 'Jo Malone Wood Sage & Sea Salt', 'gender' => 'Unisex', 'family' => 'Fresh', 'shelf' => 'Shelf 03', 'section' => 'Section B', 'season' => 'Summer', 'notes' => 'Mineral sea salt and sage', 'top_notes' => 'Sea Salt, Sage, Grapefruit', 'middle_notes' => 'Sea Salt, Sage, Iris', 'base_notes' => 'Woody Notes, Musk', 'warehouse' => 'Warehouse 2', 'concentration' => 'Cologne', 'sillage' => 'Soft', 'price' => 85.00],
            ['code' => 'JM-003', 'name' => 'Jo Malone Lime Basil & Mandarin', 'original_perfume' => 'Jo Malone Lime Basil & Mandarin', 'gender' => 'Unisex', 'family' => 'Citrus', 'shelf' => 'Shelf 03', 'section' => 'Section B', 'season' => 'Summer', 'notes' => 'Zesty lime and aromatic basil', 'top_notes' => 'Lime, Mandarin, Bergamot', 'middle_notes' => 'Basil, Jasmine, Lily of the Valley', 'base_notes' => 'Musk, Vetiver, Cedar', 'warehouse' => 'Warehouse 2', 'concentration' => 'Cologne', 'sillage' => 'Soft', 'price' => 85.00],
            ['code' => 'AC-001', 'name' => 'Acqua di Gio Profumo', 'original_perfume' => 'Giorgio Armani Acqua di Gio Profumo', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 03', 'section' => 'Section B', 'season' => 'Summer', 'notes' => 'Marine freshness with incense', 'top_notes' => 'Sea Notes, Bergamot, Mandarin', 'middle_notes' => 'Rosemary, Sage, Geranium', 'base_notes' => 'Incense, Patchouli, Musk', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 140.00],
            ['code' => 'AC-002', 'name' => 'Armani Sí', 'original_perfume' => 'Giorgio Armani Sí', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 03', 'section' => 'Section B', 'season' => 'Spring', 'notes' => 'Elegant blackcurrant nectar', 'top_notes' => 'Black Currant, Pear, Bergamot', 'middle_notes' => 'Rose, Jasmine, Freesia', 'base_notes' => 'Vanilla, Amber, Woody Notes', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 120.00],
            ['code' => 'PD-001', 'name' => 'Parfums de Marly Layton', 'original_perfume' => 'Parfums de Marly Layton', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Autumn', 'notes' => 'Spicy apple and vanilla', 'top_notes' => 'Apple, Lavender, Bergamot', 'middle_notes' => 'Jasmine, Geranium, Violet', 'base_notes' => 'Vanilla, Sandalwood, Pepper', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 230.00],
            ['code' => 'PD-002', 'name' => 'Parfums de Marly Delina', 'original_perfume' => 'Parfums de Marly Delina', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Spring', 'notes' => 'Lush Turkish rose and lychee', 'top_notes' => 'Lychee, Rhubarb, Bergamot', 'middle_notes' => 'Turkish Rose, Peony, Vanilla', 'base_notes' => 'Cashmeran, Musk, Cedar', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 240.00],
            ['code' => 'XR-001', 'name' => 'Xerjoff Naxos', 'original_perfume' => 'Xerjoff Naxos', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Autumn', 'notes' => 'Rich tobacco and honey', 'top_notes' => 'Bergamot, Lemon, Cinnamon', 'middle_notes' => 'Tobacco, Honey, Jasmine', 'base_notes' => 'Vanilla, Tonka, Labdanum', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 270.00],
            ['code' => 'XR-002', 'name' => 'Xerjoff Erba Pura', 'original_perfume' => 'Xerjoff Erba Pura', 'gender' => 'Unisex', 'family' => 'Citrus', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Summer', 'notes' => 'Sicilian citrus and vanilla', 'top_notes' => 'Orange, Grapefruit, Calabrian Bergamot', 'middle_notes' => 'Sicilian Lemon, Frangipani, Berry', 'base_notes' => 'Vanilla, Musk, White Amber', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 265.00],
            ['code' => 'MF-001', 'name' => 'Maison Francis Kurkdjian Baccarat Rouge 540', 'original_perfume' => 'MFK Baccarat Rouge 540', 'gender' => 'Unisex', 'family' => 'Oriental', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Winter', 'notes' => 'Saffron and cedar ambroxan', 'top_notes' => 'Saffron, Jasmine, Bitter Almond', 'middle_notes' => 'Amberwood, Cedar, Ambergris', 'base_notes' => 'Fir Resin, Cedar, Musk', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 325.00],
            ['code' => 'MF-002', 'name' => 'MFK Grand Soir', 'original_perfume' => 'MFK Grand Soir', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Winter', 'notes' => 'Warm amber and vanilla', 'top_notes' => 'Labdanum, Bergamot, Cistus', 'middle_notes' => 'Amber, Benzoin, Cinnamon', 'base_notes' => 'Vanilla, Tonka, Musk', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 290.00],
            ['code' => 'MF-003', 'name' => 'MFK À la Rose', 'original_perfume' => 'MFK À la Rose', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Spring', 'notes' => 'Fresh rose and violet', 'top_notes' => 'Bergamot, Violet, Lemon', 'middle_notes' => 'Rose, Jasmine, Magnolia', 'base_notes' => 'Musk, Cedar, Sandalwood', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 280.00],
            ['code' => 'VC-001', 'name' => 'Viktor & Rolf Flowerbomb', 'original_perfume' => 'Viktor & Rolf Flowerbomb', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 05', 'section' => 'Section B', 'season' => 'Spring', 'notes' => 'Explosive floral bouquet', 'top_notes' => 'Tea, Bergamot, Osmanthus', 'middle_notes' => 'Jasmine, Rose, Freesia', 'base_notes' => 'Patchouli, Musk, Vanilla', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 155.00],
            ['code' => 'VC-002', 'name' => 'Viktor & Rolf Spicebomb', 'original_perfume' => 'Viktor & Rolf Spicebomb', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 05', 'section' => 'Section B', 'season' => 'Winter', 'notes' => 'Explosive spices and leather', 'top_notes' => 'Pink Pepper, Bergamot, Grapefruit', 'middle_notes' => 'Cinnamon, Saffron, Paprika', 'base_notes' => 'Leather, Tobacco, Vetiver', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Heavy', 'price' => 120.00],
            ['code' => 'PG-001', 'name' => 'Paco Rabanne Invictus', 'original_perfume' => 'Paco Rabanne Invictus', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Summer', 'notes' => 'Fresh and sporty aquatic', 'top_notes' => 'Grapefruit, Mandarin, Sea Notes', 'middle_notes' => 'Bay Leaf, Jasmine, Guaiac Wood', 'base_notes' => 'Ambergris, Cedar, Musk', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 95.00],
            ['code' => 'PG-002', 'name' => 'Paco Rabanne Lady Million', 'original_perfume' => 'Paco Rabanne Lady Million', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Spring', 'notes' => 'Sparkling floral with honey', 'top_notes' => 'Raspberry, Neroli, Bitter Orange', 'middle_notes' => 'Orange Blossom, Jasmine, Honey', 'base_notes' => 'Patchouli, Amber, Honey', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 105.00],
            ['code' => 'CK-001', 'name' => 'Calvin Klein CK One', 'original_perfume' => 'Calvin Klein CK One', 'gender' => 'Unisex', 'family' => 'Citrus', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Summer', 'notes' => 'Fresh citrus and green tea', 'top_notes' => 'Pineapple, Bergamot, Cardamom', 'middle_notes' => 'Green Tea, Violet, Lily of the Valley', 'base_notes' => 'Musk, Amber, Cedar', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Soft', 'price' => 55.00],
            ['code' => 'CK-002', 'name' => 'Calvin Klein Euphoria', 'original_perfume' => 'Calvin Klein Euphoria', 'gender' => 'Kadın', 'family' => 'Oriental', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Autumn', 'notes' => 'Seductive pomegranate and orchid', 'top_notes' => 'Pomegranate, Persimmon, Green Notes', 'middle_notes' => 'Orchid, Lotus, Black Violet', 'base_notes' => 'Musk, Amber, Mahogany', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 75.00],
            ['code' => 'VS-001', 'name' => 'Versace Eros', 'original_perfume' => 'Versace Eros', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Summer', 'notes' => 'Bold mint and green apple', 'top_notes' => 'Mint, Green Apple, Lemon', 'middle_notes' => 'Tonka, Ambroxan, Geranium', 'base_notes' => 'Cedar, Vetiver, Oakmoss', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Heavy', 'price' => 90.00],
            ['code' => 'VS-002', 'name' => 'Versace Bright Crystal', 'original_perfume' => 'Versace Bright Crystal', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Spring', 'notes' => 'Delicate peony and yuzu', 'top_notes' => 'Yuzu, Pomegranate, Ice Crystal', 'middle_notes' => 'Peony, Lotus, Magnolia', 'base_notes' => 'Musk, Amber, Mahogany', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Soft', 'price' => 85.00],
            ['code' => 'VS-003', 'name' => 'Versace Dylan Blue', 'original_perfume' => 'Versace Dylan Blue', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Summer', 'notes' => 'Fresh aquatic with fig leaves', 'top_notes' => 'Fig Leaves, Grapefruit, Aquatic Notes', 'middle_notes' => 'Patchouli, Black Pepper, Violet', 'base_notes' => 'Musk, Incense, Saffron', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 90.00],
            ['code' => 'GD-001', 'name' => 'Gucci Bloom', 'original_perfume' => 'Gucci Bloom', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 06', 'section' => 'Section C', 'season' => 'Spring', 'notes' => 'Rich tuberose and jasmine', 'top_notes' => 'Tuberose, Jasmine, Rangoon Creeper', 'middle_notes' => 'Tuberose, Jasmine, Iris', 'base_notes' => 'Sandalwood, Musk, Vanilla', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 135.00],
            ['code' => 'GD-002', 'name' => 'Gucci Guilty', 'original_perfume' => 'Gucci Guilty', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 06', 'section' => 'Section C', 'season' => 'Autumn', 'notes' => 'Sexy leather and patchouli', 'top_notes' => 'Lemon, Lavender, Bergamot', 'middle_notes' => 'Orange Blossom, Neroli, Cedar', 'base_notes' => 'Patchouli, Leather, Amber', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 110.00],
            ['code' => 'GD-003', 'name' => 'Gucci Flora Gorgeous Jasmine', 'original_perfume' => 'Gucci Flora', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 06', 'section' => 'Section C', 'season' => 'Spring', 'notes' => 'Sweet jasmine and sandalwood', 'top_notes' => 'Jasmine, Mandarin, Bergamot', 'middle_notes' => 'Jasmine, Rose, Ylang-Ylang', 'base_notes' => 'Sandalwood, Vanilla, Patchouli', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 125.00],
            ['code' => 'BG-001', 'name' => 'Burberry Her', 'original_perfume' => 'Burberry Her', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 06', 'section' => 'Section C', 'season' => 'Spring', 'notes' => 'Fruity floral with strawberry', 'top_notes' => 'Strawberry, Raspberry, Blackberry', 'middle_notes' => 'Jasmine, Violet, Lily of the Valley', 'base_notes' => 'Musk, Amber, Woody Notes', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 110.00],
            ['code' => 'BG-002', 'name' => 'Burberry London', 'original_perfume' => 'Burberry London', 'gender' => 'Erkek', 'family' => 'Woody', 'shelf' => 'Shelf 06', 'section' => 'Section C', 'season' => 'Winter', 'notes' => 'Warm tobacco and leather', 'top_notes' => 'Bergamot, Lavender, Black Pepper', 'middle_notes' => 'Leather, Mimosa, Port Wine', 'base_notes' => 'Tobacco, Oakmoss, Cedar', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 75.00],
            ['code' => 'HV-001', 'name' => 'Hermès Terre d\'Hermès', 'original_perfume' => 'Hermès Terre d\'Hermès', 'gender' => 'Erkek', 'family' => 'Woody', 'shelf' => 'Shelf 06', 'section' => 'Section D', 'season' => 'Autumn', 'notes' => 'Earthy vetiver and flint', 'top_notes' => 'Orange, Grapefruit, Flint', 'middle_notes' => 'Pepper, Geranium, Cedar', 'base_notes' => 'Vetiver, Oakmoss, Benzoin', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 130.00],
            ['code' => 'HV-002', 'name' => 'Hermès Twilly', 'original_perfume' => 'Hermès Twilly', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 06', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Playful ginger and tuberose', 'top_notes' => 'Ginger, Bergamot, Lemon', 'middle_notes' => 'Tuberose, Jasmine, Gardenia', 'base_notes' => 'Sandalwood, Musk, Vanilla', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 120.00],
            ['code' => 'LM-001', 'name' => 'Lalique Encre Noire', 'original_perfume' => 'Lalique Encre Noire', 'gender' => 'Erkek', 'family' => 'Woody', 'shelf' => 'Shelf 07', 'section' => 'Section D', 'season' => 'Winter', 'notes' => 'Dark vetiver and cypress', 'top_notes' => 'Cypress, Bergamot, Lemon', 'middle_notes' => 'Vetiver, Cashmeran, Cedar', 'base_notes' => 'Vetiver, Musk, Oakmoss', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 50.00],
            ['code' => 'LM-002', 'name' => 'Lalique Amethyst', 'original_perfume' => 'Lalique Amethyst', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 07', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Rich blackberry and violet', 'top_notes' => 'Blackberry, Mimosa, Bergamot', 'middle_notes' => 'Violet, Rose, Jasmine', 'base_notes' => 'Sandalwood, Musk, Cedar', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 55.00],
            ['code' => 'MN-001', 'name' => 'Montblanc Explorer', 'original_perfume' => 'Montblanc Explorer', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 07', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Adventurous vetiver and leather', 'top_notes' => 'Bergamot, Clary Sage, Pink Pepper', 'middle_notes' => 'Vetiver, Leather, Cedar', 'base_notes' => 'Amber, Akigalawood, Musk', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 85.00],
            ['code' => 'MN-002', 'name' => 'Montblanc Signature', 'original_perfume' => 'Montblanc Signature', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 07', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Elegant magnolia and almond', 'top_notes' => 'Mandarin, Almond, Bergamot', 'middle_notes' => 'Magnolia, Jasmine, Orange Blossom', 'base_notes' => 'Sandalwood, Vanilla, Musk', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Parfum', 'sillage' => 'Soft', 'price' => 90.00],
            ['code' => 'RB-001', 'name' => 'Ralph Lauren Polo Blue', 'original_perfume' => 'Ralph Lauren Polo Blue', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 07', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Fresh melon and cucumber', 'top_notes' => 'Melon, Cucumber, Mandarin', 'middle_notes' => 'Sage, Lavender, Geranium', 'base_notes' => 'Suede, Oakmoss, Musk', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Toilette', 'sillage' => 'Soft', 'price' => 85.00],
            ['code' => 'RB-002', 'name' => 'Ralph Lauren Romance', 'original_perfume' => 'Ralph Lauren Romance', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 07', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Tender rose and daffodil', 'top_notes' => 'Rose, Violet, Bergamot', 'middle_notes' => 'Daffodil, Jasmine, Lily', 'base_notes' => 'Sandalwood, Musk, Oakmoss', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 80.00],
            ['code' => 'DG-001', 'name' => 'Dolce & Gabbana Light Blue', 'original_perfume' => 'D&G Light Blue', 'gender' => 'Kadın', 'family' => 'Citrus', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Sicilian citrus and cedar', 'top_notes' => 'Sicilian Lemon, Granny Smith Apple, Cedar', 'middle_notes' => 'Jasmine, White Rose, Bamboo', 'base_notes' => 'Cedar, Musk, Amber', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 100.00],
            ['code' => 'DG-002', 'name' => 'Dolce & Gabbana The One', 'original_perfume' => 'D&G The One', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Autumn', 'notes' => 'Warm tobacco and amber', 'top_notes' => 'Grapefruit, Coriander, Basil', 'middle_notes' => 'Cardamom, Ginger, Orange Blossom', 'base_notes' => 'Tobacco, Amber, Cedar', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 105.00],
            ['code' => 'DG-003', 'name' => 'Dolce & Gabbana Pour Femme', 'original_perfume' => 'D&G Pour Femme', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Delicate raspberry and marshmallow', 'top_notes' => 'Raspberry, Neroli, Bergamot', 'middle_notes' => 'Jasmine, Rose, Marshmallow', 'base_notes' => 'Vanilla, Sandalwood, Tonka', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 110.00],
            ['code' => 'NH-001', 'name' => 'Nishane Hacivat', 'original_perfume' => 'Nishane Hacivat', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Modern pineapple and oakmoss', 'top_notes' => 'Pineapple, Grapefruit, Bergamot', 'middle_notes' => 'Cedar, Jasmine, Patchouli', 'base_notes' => 'Oakmoss, Musk, Sandalwood', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 260.00],
            ['code' => 'NH-002', 'name' => 'Nishane Ani', 'original_perfume' => 'Nishane Ani', 'gender' => 'Kadın', 'family' => 'Oriental', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Winter', 'notes' => 'Creamy vanilla and bergamot', 'top_notes' => 'Bergamot, Cardamom, Pink Pepper', 'middle_notes' => 'Vanilla, Ginger, Jasmine', 'base_notes' => 'Vanilla, Ambergris, Oakmoss', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 255.00],
            ['code' => 'AD-001', 'name' => 'Amouage Interlude Man', 'original_perfume' => 'Amouage Interlude', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Winter', 'notes' => 'Dark incense and oregano', 'top_notes' => 'Bergamot, Oregano, Pimento', 'middle_notes' => 'Incense, Amber, Labdanum', 'base_notes' => 'Leather, Sandalwood, Vanilla', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 310.00],
            ['code' => 'AD-002', 'name' => 'Amouage Reflection Man', 'original_perfume' => 'Amouage Reflection', 'gender' => 'Erkek', 'family' => 'Floral', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Elegant floral and woody', 'top_notes' => 'Bergamot, Grapefruit, Cardamom', 'middle_notes' => 'Jasmine, Rose, Iris', 'base_notes' => 'Cedar, Vetiver, Sandalwood', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 320.00],
            ['code' => 'BV-001', 'name' => 'Byredo Gypsy Water', 'original_perfume' => 'Byredo Gypsy Water', 'gender' => 'Unisex', 'family' => 'Fresh', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Woodsy vanilla and citrus', 'top_notes' => 'Bergamot, Lemon, Juniper', 'middle_notes' => 'Pine, Orris, Pepper', 'base_notes' => 'Vanilla, Sandalwood, Amber', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Soft', 'price' => 190.00],
            ['code' => 'BV-002', 'name' => 'Byredo Bal d\'Afrique', 'original_perfume' => 'Byredo Bal d\'Afrique', 'gender' => 'Unisex', 'family' => 'Fresh', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Warm marigold and vetiver', 'top_notes' => 'Bergamot, Lemon, Marigold', 'middle_notes' => 'Violet, Jasmine, Neroli', 'base_notes' => 'Vetiver, Cedar, Musk', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 195.00],
            ['code' => 'BV-003', 'name' => 'Byredo Mojave Ghost', 'original_perfume' => 'Byredo Mojave Ghost', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Desert floral and magnolia', 'top_notes' => 'Sapodilla, Ambrette, Bergamot', 'middle_notes' => 'Magnolia, Violet, Sandalwood', 'base_notes' => 'Cedar, Musk, Amber', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 190.00],
            ['code' => 'LV-001', 'name' => 'Louis Vuitton Ombre Nomade', 'original_perfume' => 'Louis Vuitton Ombre Nomade', 'gender' => 'Erkek', 'family' => 'Woody', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Winter', 'notes' => 'Rich oud and raspberry', 'top_notes' => 'Raspberry, Saffron, Cardamom', 'middle_notes' => 'Oud, Incense, Guaiac Wood', 'base_notes' => 'Leather, Cedar, Patchouli', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 350.00],
            ['code' => 'LV-002', 'name' => 'Louis Vuitton Pacific Chill', 'original_perfume' => 'Louis Vuitton Pacific Chill', 'gender' => 'Unisex', 'family' => 'Fresh', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Refreshing blackcurrant and mint', 'top_notes' => 'Blackcurrant, Lemon, Mint', 'middle_notes' => 'Orange, Coriander, Geranium', 'base_notes' => 'Cedar, Sandalwood, Musk', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 330.00],
            ['code' => 'EL-001', 'name' => 'Estée Lauder Modern Muse', 'original_perfume' => 'Estée Lauder Modern Muse', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Modern floral with honey', 'top_notes' => 'Mandarin, Bergamot, Honey', 'middle_notes' => 'Jasmine, Rose, Tuberose', 'base_notes' => 'Musk, Amber, Sandalwood', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 105.00],
            ['code' => 'EL-002', 'name' => 'Estée Lauder Pleasures', 'original_perfume' => 'Estée Lauder Pleasures', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 09', 'section' => 'Section D', 'season' => 'Spring', 'notes' => 'Fresh floral with lily and peony', 'top_notes' => 'Lily, Violet, Bergamot', 'middle_notes' => 'Peony, Rose, Jasmine', 'base_notes' => 'Sandalwood, Musk, Amber', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 95.00],
            ['code' => 'CR-004', 'name' => 'Creed Royal Oud', 'original_perfume' => 'Creed Royal Oud', 'gender' => 'Erkek', 'family' => 'Woody', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Winter', 'notes' => 'Regal oud and cedar', 'top_notes' => 'Lemon, Bergamot, Angelica', 'middle_notes' => 'Cedar, Sandalwood, Frankincense', 'base_notes' => 'Oud, Musk, Ambergris', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 350.00],
            ['code' => 'TF-004', 'name' => 'Tom Ford Black Orchid', 'original_perfume' => 'Tom Ford Black Orchid', 'gender' => 'Kadın', 'family' => 'Oriental', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Winter', 'notes' => 'Luxurious black orchid and truffle', 'top_notes' => 'Truffle, Black Currant, Bergamot', 'middle_notes' => 'Black Orchid, Lotus, Jasmine', 'base_notes' => 'Patchouli, Incense, Vanilla', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 175.00],
            ['code' => 'CH-001', 'name' => 'Chanel Allure Homme Sport', 'original_perfume' => 'Chanel Allure Homme Sport', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Summer', 'notes' => 'Fresh and energetic sport scent', 'top_notes' => 'Mandarin, Sea Notes, Aldehydes', 'middle_notes' => 'Pepper, Cedar, Nutmeg', 'base_notes' => 'Tonka, Vanilla, Musk', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 130.00],
            ['code' => 'PD-003', 'name' => 'Parfums de Marly Herod', 'original_perfume' => 'Parfums de Marly Herod', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Winter', 'notes' => 'Spicy tobacco and cinnamon', 'top_notes' => 'Cinnamon, Pepper, Bergamot', 'middle_notes' => 'Tobacco, Incense, Osmanthus', 'base_notes' => 'Vanilla, Cedar, Musk', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 235.00],
            ['code' => 'XR-003', 'name' => 'Xerjoff Accento', 'original_perfume' => 'Xerjoff Accento', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Spring', 'notes' => 'Italian citrus and rose', 'top_notes' => 'Bergamot, Lemon, Orange', 'middle_notes' => 'Rose, Jasmine, Violet', 'base_notes' => 'Musk, Sandalwood, Vanilla', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 260.00],
            ['code' => 'PG-003', 'name' => 'Paco Rabanne 1 Million', 'original_perfume' => 'Paco Rabanne 1 Million', 'gender' => 'Erkek', 'family' => 'Oriental', 'shelf' => 'Shelf 05', 'section' => 'Section C', 'season' => 'Autumn', 'notes' => 'Rich cinnamon and leather', 'top_notes' => 'Cinnamon, Mint, Grapefruit', 'middle_notes' => 'Rose, Cinnamon, Spices', 'base_notes' => 'Leather, Amber, Cedar', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Toilette', 'sillage' => 'Heavy', 'price' => 100.00],
            ['code' => 'HV-003', 'name' => 'Hermès Un Jardin Sur Le Nil', 'original_perfume' => 'Hermès Un Jardin Sur Le Nil', 'gender' => 'Unisex', 'family' => 'Fresh', 'shelf' => 'Shelf 06', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Green mango and lotus', 'top_notes' => 'Green Mango, Grapefruit, Carrot', 'middle_notes' => 'Lotus, Hyacinth, Bulrush', 'base_notes' => 'Sycamore, Musk, Incense', 'warehouse' => 'Warehouse 4', 'concentration' => 'Eau de Toilette', 'sillage' => 'Soft', 'price' => 120.00],
            ['code' => 'NH-003', 'name' => 'Nishane Wulong Cha', 'original_perfume' => 'Nishane Wulong Cha', 'gender' => 'Unisex', 'family' => 'Citrus', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Sparkling tea and citrus', 'top_notes' => 'Bergamot, Mandarin, Fig', 'middle_notes' => 'Oolong Tea, Jasmine, Nutmeg', 'base_notes' => 'Musk, Oakmoss, Woody Notes', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 250.00],
            ['code' => 'AD-003', 'name' => 'Amouage Beach Hut Man', 'original_perfume' => 'Amouage Beach Hut', 'gender' => 'Erkek', 'family' => 'Green', 'shelf' => 'Shelf 08', 'section' => 'Section D', 'season' => 'Summer', 'notes' => 'Fresh ivy and mint', 'top_notes' => 'Mint, Ivy, Bergamot', 'middle_notes' => 'Geranium, Jasmine, Clary Sage', 'base_notes' => 'Cedar, Sandalwood, Musk', 'warehouse' => 'Warehouse 5', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 310.00],
            ['code' => 'MF-004', 'name' => 'MFK Oud Satin Mood', 'original_perfume' => 'MFK Oud Satin Mood', 'gender' => 'Unisex', 'family' => 'Oriental', 'shelf' => 'Shelf 04', 'section' => 'Section B', 'season' => 'Winter', 'notes' => 'Luxurious rose and oud', 'top_notes' => 'Rose, Bergamot, Violet', 'middle_notes' => 'Oud, Jasmine, Rose', 'base_notes' => 'Vanilla, Benzoin, Amber', 'warehouse' => 'Warehouse 3', 'concentration' => 'Eau de Parfum', 'sillage' => 'Heavy', 'price' => 320.00],
            ['code' => 'JM-004', 'name' => 'Jo Malone Pomegranate Noir', 'original_perfume' => 'Jo Malone Pomegranate Noir', 'gender' => 'Kadın', 'family' => 'Oriental', 'shelf' => 'Shelf 03', 'section' => 'Section B', 'season' => 'Autumn', 'notes' => 'Dark pomegranate and woods', 'top_notes' => 'Pomegranate, Raspberry, Rhubarb', 'middle_notes' => 'Casablanca Lily, Jasmine, Pink Pepper', 'base_notes' => 'Guaiac Wood, Patchouli, Amber', 'warehouse' => 'Warehouse 2', 'concentration' => 'Cologne', 'sillage' => 'Moderate', 'price' => 85.00],
            ['code' => 'DX-004', 'name' => 'Dior J\'adore', 'original_perfume' => 'Dior J\'adore', 'gender' => 'Kadın', 'family' => 'Floral', 'shelf' => 'Shelf 01', 'section' => 'Section A', 'season' => 'Spring', 'notes' => 'Elegant floral bouquet', 'top_notes' => 'Pear, Melon, Peach', 'middle_notes' => 'Jasmine, Rose, Lily of the Valley', 'base_notes' => 'Sandalwood, Cedar, Musk', 'warehouse' => 'Warehouse 1', 'concentration' => 'Eau de Parfum', 'sillage' => 'Moderate', 'price' => 140.00],
            ['code' => 'BL-002', 'name' => 'Chanel Platinum Égoïste', 'original_perfume' => 'Chanel Platinum Égoïste', 'gender' => 'Erkek', 'family' => 'Fresh', 'shelf' => 'Shelf 02', 'section' => 'Section A', 'season' => 'Summer', 'notes' => 'Clean lavender and rosemary', 'top_notes' => 'Lavender, Rosemary, Bergamot', 'middle_notes' => 'Geranium, Clary Sage, Jasmine', 'base_notes' => 'Sandalwood, Cedar, Oakmoss', 'warehouse' => 'Warehouse 2', 'concentration' => 'Eau de Toilette', 'sillage' => 'Moderate', 'price' => 135.00],
        ];

        $seasonMap = [
            'Summer' => 'summer',
            'Autumn' => 'autumn',
            'Spring' => 'spring',
            'Winter' => 'winter',
        ];

        $genderMap = [
            'Erkek' => 'erkek',
            'Kadın' => 'kadin',
            'Unisex' => 'unisex',
        ];

        $multilingualFields = ['name', 'original_perfume', 'family', 'notes', 'top_notes', 'middle_notes', 'base_notes', 'concentration', 'sillage'];

        foreach ($perfumes as $perfume) {
            foreach ($multilingualFields as $field) {
                if (isset($perfume[$field]) && is_string($perfume[$field])) {
                    $perfume[$field] = ['en' => $perfume[$field], 'ar' => $perfume[$field]];
                }
            }

            $seasonSlug = $seasonMap[$perfume['season']] ?? null;
            $genderSlug = $genderMap[$perfume['gender']] ?? null;
            unset($perfume['gender'], $perfume['season']);

            $created = Perfume::create($perfume);

            if ($seasonSlug) {
                $season = Season::where('slug', $seasonSlug)->first();
                if ($season) {
                    $created->seasons()->attach($season);
                }
            }

            if ($genderSlug) {
                $category = FragranceCategory::where('slug', $genderSlug)->first();
                if ($category) {
                    $created->fragranceCategories()->attach($category);
                }
            }
        }
    }
}
