import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Locale = 'en' | 'tr' | 'ar';

interface LanguageContextType {
    locale: Locale;
    setLocale: (locale: Locale) => void;
    t: (key: string) => string;
    dir: 'ltr' | 'rtl';
}

const translations: Record<Locale, Record<string, string>> = {
    en: {
        'nav.perfumes': 'Perfumes',
        'nav.oils': 'Oils',
        'nav.manage': 'Manage',
        'nav.dashboard': 'Dashboard',
        'nav.repository': 'Repository',
        'nav.documentation': 'Documentation',
        'nav.nav_menu': 'Navigation Menu',
        'user.settings': 'Settings',
        'user.logout': 'Log out',
        'welcome.dashboard': 'Dashboard',
        'welcome.login': 'Log in',
        'welcome.register': 'Register',
        'welcome.getting_started': "Let's get started",
        'welcome.description': 'Laravel has an incredibly rich ecosystem. We suggest you start with the following.',
        'welcome.read_docs': 'Read the',
        'welcome.documentation': 'Documentation',
        'welcome.watch_tutorials': 'Watch video tutorials at',
        'welcome.laracasts': 'Laracasts',
        'welcome.deploy_now': 'Deploy now',
        'perfume.title': 'Perfumes',
        'perfume.manage': 'Manage Perfumes',
        'perfume.manage.desc': 'Add, edit or remove perfumes from inventory',
        'perfume.add': 'Add Perfume',
        'perfume.edit': 'Edit Perfume',
        'perfume.delete': 'Delete Perfume',
        'perfume.fields': 'Fields',
        'perfume.search': 'Search perfumes...',
        'perfume.all': 'All Perfumes',
        'perfume.total': 'Total Perfumes',
        'perfume.no_results': 'No perfumes found',
        'perfume.cancel': 'Cancel',
        'perfume.create': 'Create',
        'perfume.update': 'Update',
        'perfume.delete_confirm': 'Are you sure you want to delete "{name}" ({code})? This action cannot be undone.',
        'perfume.browse': 'Perfumes',
        'perfume.browse.desc': 'Manage your perfume inventory',
        'perfume.add_btn': 'Add Perfume',
        'perfume.search_placeholder': 'Search by name, code or original perfume...',
        'perfume.search_btn': 'Search',
        'perfume.all_tab': 'All',
        'perfume.erkek_tab': 'Frequency Erkek',
        'perfume.kadin_tab': 'Frequency Kadın',
        'perfume.unisex_tab': 'Frequency Unisex',
        'perfume.niche_tab': 'Niche',
        'perfume.oil_tab': 'Oils',
        'perfume.filter_all': 'All',
        'perfume.filter_summer': 'Summer',
        'perfume.filter_autumn': 'Autumn',
        'perfume.filter_spring': 'Spring',
        'perfume.filter_winter': 'Winter',
        'perfume.gender': 'Gender',
        'perfume.family': 'Family',
        'perfume.shelf': 'Shelf',
        'perfume.section': 'Section',
        'perfume.clear_filters': 'Clear Filters',
        'perfume.total_count': 'Total Perfumes',
        'perfume.men_count': 'Men',
        'perfume.women_count': 'Women',
        'perfume.niche_count': 'Niche',
        'perfume.results_found': 'results found',
        'perfume.sort_by': 'Sort By',
        'perfume.view_details': 'View Details',
        'perfume.frequency_erkek': 'Frequency Erkek',
        'perfume.frequency_kadin': 'Frequency Kadın',
        'perfume.per_page': 'per page',
        'oil.title': 'Oils',
        'oil.manage': 'Manage Oils',
        'oil.manage.desc': 'Add, edit or remove oils from inventory',
        'oil.add': 'Add Oil',
        'oil.edit': 'Edit Oil',
        'oil.delete': 'Delete Oil',
        'oil.fields': 'Fields',
        'oil.search': 'Search oils...',
        'oil.all': 'All Oils',
        'oil.total': 'Total Oils',
        'oil.no_results': 'No oils found',
        'oil.cancel': 'Cancel',
        'oil.create': 'Create',
        'oil.update': 'Update',
        'oil.delete_confirm': 'Are you sure you want to delete "{name}" ({code})? This action cannot be undone.',
        'oil.browse': 'Oils',
        'oil.browse.desc': 'Manage your oil inventory',
        'oil.add_btn': 'Add Oil',
        'oil.search_placeholder': 'Search by name, code, brand or supplier...',
        'oil.search_btn': 'Search',
        'oil.all_tab': 'All',
        'oil.essential_tab': 'Essential',
        'oil.fragrance_tab': 'Fragrance',
        'oil.carrier_tab': 'Carrier',
        'oil.blend_tab': 'Blend',
        'oil.category': 'Category',
        'oil.shelf': 'Shelf',
        'oil.section': 'Section',
        'oil.clear_filters': 'Clear Filters',
        'oil.total_count': 'Total Oils',
        'oil.essential_count': 'Essential',
        'oil.fragrance_count': 'Fragrance',
        'oil.carrier_count': 'Carrier',
        'oil.results_found': 'results found',
        'oil.sort_by': 'Sort By',
        'oil.view_details': 'View Details',
        'oil.essential': 'Essential',
        'oil.fragrance': 'Fragrance',
        'oil.carrier': 'Carrier',
        'oil.pricing': 'Pricing',
        'field.name': 'Name',
        'field.code': 'Code',
        'field.original_perfume': 'Original Perfume',
        'field.image': 'Image',
        'field.gender': 'Gender',
        'field.family': 'Family',
        'field.shelf': 'Shelf',
        'field.section': 'Section',
        'field.season': 'Season',
        'field.notes': 'Notes',
        'field.top_notes': 'Top Notes',
        'field.middle_notes': 'Middle Notes',
        'field.base_notes': 'Base Notes',
        'field.warehouse': 'Warehouse',
        'field.concentration': 'Concentration',
        'field.sillage': 'Sillage',
        'field.price': 'Price',
        'field.category': 'Category',
        'field.brand': 'Brand',
        'field.volume': 'Volume',
        'field.supplier': 'Supplier',
        'field.type': 'Type',
        'field.slug': 'Slug',
        'field.fragrance_categories': 'Fragrance Categories',
        'field.seasons': 'Seasons',
        'field.select_category': 'Select a category',
        'field.image_choose': 'Choose File',
        'field.image_keep': 'Current image will be kept',
        'field.image_none': 'No file chosen',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'gender.unisex': 'Unisex',
        'season.summer': 'Summer',
        'season.autumn': 'Autumn',
        'season.spring': 'Spring',
        'season.winter': 'Winter',
        'season.manage': 'Manage Seasons',
        'season.manage.desc': 'Add, edit or remove seasons',
        'season.add': 'Add Season',
        'season.edit': 'Edit Season',
        'season.all': 'All Seasons',
        'season.no_results': 'No seasons found',
        'season.cancel': 'Cancel',
        'season.create': 'Create',
        'season.update': 'Update',
        'season.delete_confirm': 'Are you sure you want to delete "{name}"?',
        'category.manage': 'Manage Fragrance Categories',
        'category.manage.desc': 'Add, edit or remove fragrance categories',
        'category.add': 'Add Category',
        'category.edit': 'Edit Category',
        'category.all': 'All Categories',
        'category.no_results': 'No categories found',
        'category.cancel': 'Cancel',
        'category.create': 'Create',
        'category.update': 'Update',
        'category.delete_confirm': 'Are you sure you want to delete "{name}"?',
        'sillage_level.manage': 'Manage Sillage Levels',
        'sillage_level.manage.desc': 'Add, edit or remove sillage levels',
        'sillage_level.add': 'Add Sillage Level',
        'sillage_level.edit': 'Edit Sillage Level',
        'sillage_level.all': 'All Sillage Levels',
        'sillage_level.no_results': 'No sillage levels found',
        'sillage_level.cancel': 'Cancel',
        'sillage_level.create': 'Create',
        'sillage_level.update': 'Update',
        'sillage_level.delete_confirm': 'Are you sure you want to delete "{name}"?',
        'field.sillage_levels': 'Sillage Levels',
        'field.select_category': 'Select a category',
    },
    tr: {
        'nav.perfumes': 'Parfümler',
        'nav.oils': 'Yağlar',
        'nav.manage': 'Yönet',
        'nav.dashboard': 'Kontrol Paneli',
        'nav.repository': 'Depo',
        'nav.documentation': 'Dokümantasyon',
        'nav.nav_menu': 'Navigasyon Menüsü',
        'user.settings': 'Ayarlar',
        'user.logout': 'Çıkış Yap',
        'welcome.dashboard': 'Kontrol Paneli',
        'welcome.login': 'Giriş Yap',
        'welcome.register': 'Kayıt Ol',
        'welcome.getting_started': 'Hadi başlayalım',
        'welcome.description': "Laravel'in inanılmaz zengin bir ekosistemi var. Aşağıdakilerle başlamanızı öneririz.",
        'welcome.read_docs': 'Şurayı oku:',
        'welcome.documentation': 'Dokümantasyon',
        'welcome.watch_tutorials': 'Video eğitimlerini izleyin:',
        'welcome.laracasts': 'Laracasts',
        'welcome.deploy_now': 'Şimdi Yayınla',
        'perfume.title': 'Parfümler',
        'perfume.browse': 'Parfümler',
        'perfume.browse.desc': 'Parfüm envanterinizi yönetin',
        'perfume.add_btn': 'Parfüm Ekle',
        'perfume.search_placeholder': 'İsim, kod veya orijinal parfüme göre ara...',
        'perfume.search_btn': 'Ara',
        'perfume.all_tab': 'Tümü',
        'perfume.erkek_tab': 'Frequency Erkek',
        'perfume.kadin_tab': 'Frequency Kadın',
        'perfume.unisex_tab': 'Frequency Unisex',
        'perfume.niche_tab': 'Niche',
        'perfume.oil_tab': 'Yağlar',
        'perfume.filter_all': 'Tümü',
        'perfume.filter_summer': 'Yaz',
        'perfume.filter_autumn': 'Sonbahar',
        'perfume.filter_spring': 'İlkbahar',
        'perfume.filter_winter': 'Kış',
        'perfume.gender': 'Cinsiyet',
        'perfume.family': 'Aile',
        'perfume.shelf': 'Raf',
        'perfume.section': 'Bölüm',
        'perfume.clear_filters': 'Filtreleri Temizle',
        'perfume.total_count': 'Toplam Parfüm',
        'perfume.men_count': 'Erkek',
        'perfume.women_count': 'Kadın',
        'perfume.niche_count': 'Niche',
        'perfume.results_found': 'sonuç bulundu',
        'perfume.sort_by': 'Sırala',
        'perfume.view_details': 'Detayları Gör',
        'perfume.frequency_erkek': 'Frequency Erkek',
        'perfume.frequency_kadin': 'Frequency Kadın',
        'perfume.per_page': 'sayfa başına',
        'perfume.manage': 'Parfümleri Yönet',
        'perfume.manage.desc': 'Envantere parfüm ekle, düzenle veya kaldır',
        'perfume.add': 'Parfüm Ekle',
        'perfume.edit': 'Parfümü Düzenle',
        'perfume.delete': 'Parfümü Sil',
        'perfume.fields': 'Alanlar',
        'perfume.search': 'Parfüm ara...',
        'perfume.all': 'Tüm Parfümler',
        'perfume.total': 'Toplam Parfüm',
        'perfume.no_results': 'Parfüm bulunamadı',
        'perfume.cancel': 'İptal',
        'perfume.create': 'Oluştur',
        'perfume.update': 'Güncelle',
        'perfume.delete_confirm': '"{name}" ({code}) silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
        'oil.title': 'Yağlar',
        'oil.manage': 'Yağları Yönet',
        'oil.manage.desc': 'Envantere yağ ekle, düzenle veya kaldır',
        'oil.add': 'Yağ Ekle',
        'oil.edit': 'Yağı Düzenle',
        'oil.delete': 'Yağı Sil',
        'oil.fields': 'Alanlar',
        'oil.search': 'Yağ ara...',
        'oil.all': 'Tüm Yağlar',
        'oil.total': 'Toplam Yağ',
        'oil.no_results': 'Yağ bulunamadı',
        'oil.cancel': 'İptal',
        'oil.create': 'Oluştur',
        'oil.update': 'Güncelle',
        'oil.delete_confirm': '"{name}" ({code}) silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
        'oil.browse': 'Yağlar',
        'oil.browse.desc': 'Yağ envanterinizi yönetin',
        'oil.add_btn': 'Yağ Ekle',
        'oil.search_placeholder': 'İsim, kod, marka veya tedarikçiye göre ara...',
        'oil.search_btn': 'Ara',
        'oil.all_tab': 'Tümü',
        'oil.essential_tab': 'Esansiyel',
        'oil.fragrance_tab': 'Koku',
        'oil.carrier_tab': 'Taşıyıcı',
        'oil.blend_tab': 'Karışım',
        'oil.category': 'Kategori',
        'oil.shelf': 'Raf',
        'oil.section': 'Bölüm',
        'oil.clear_filters': 'Filtreleri Temizle',
        'oil.total_count': 'Toplam Yağ',
        'oil.essential_count': 'Esansiyel',
        'oil.fragrance_count': 'Koku',
        'oil.carrier_count': 'Taşıyıcı',
        'oil.results_found': 'sonuç bulundu',
        'oil.sort_by': 'Sırala',
        'oil.view_details': 'Detayları Gör',
        'oil.essential': 'Esansiyel',
        'oil.fragrance': 'Koku',
        'oil.carrier': 'Taşıyıcı',
        'oil.pricing': 'Fiyatlandırma',
        'field.name': 'İsim',
        'field.code': 'Kod',
        'field.original_perfume': 'Orijinal Parfüm',
        'field.image': 'Görsel',
        'field.gender': 'Cinsiyet',
        'field.family': 'Aile',
        'field.shelf': 'Raf',
        'field.section': 'Bölüm',
        'field.season': 'Mevsim',
        'field.notes': 'Notlar',
        'field.top_notes': 'Üst Notalar',
        'field.middle_notes': 'Orta Notalar',
        'field.base_notes': 'Alt Notalar',
        'field.warehouse': 'Depo',
        'field.concentration': 'Konsantrasyon',
        'field.sillage': 'Fark Edilirlik',
        'field.price': 'Fiyat',
        'field.category': 'Kategori',
        'field.brand': 'Marka',
        'field.volume': 'Hacim',
        'field.supplier': 'Tedarikçi',
        'field.type': 'Tür',
        'field.slug': 'Bağlantı',
        'field.fragrance_categories': 'Koku Kategorileri',
        'field.seasons': 'Mevsimler',
        'field.image_choose': 'Dosya Seç',
        'field.image_keep': 'Mevcut görsel korunacak',
        'field.image_none': 'Dosya seçilmedi',
        'gender.male': 'Erkek',
        'gender.female': 'Kadın',
        'gender.unisex': 'Uniseks',
        'season.summer': 'Yaz',
        'season.autumn': 'Sonbahar',
        'season.spring': 'İlkbahar',
        'season.winter': 'Kış',
        'season.manage': 'Mevsimleri Yönet',
        'season.manage.desc': 'Mevsim ekle, düzenle veya kaldır',
        'season.add': 'Mevsim Ekle',
        'season.edit': 'Mevsim Düzenle',
        'season.all': 'Tüm Mevsimler',
        'season.no_results': 'Mevsim bulunamadı',
        'season.cancel': 'İptal',
        'season.create': 'Oluştur',
        'season.update': 'Güncelle',
        'season.delete_confirm': '"{name}" silmek istediğinize emin misiniz?',
        'category.manage': 'Koku Kategorilerini Yönet',
        'category.manage.desc': 'Koku kategorisi ekle, düzenle veya kaldır',
        'category.add': 'Kategori Ekle',
        'category.edit': 'Kategori Düzenle',
        'category.all': 'Tüm Kategoriler',
        'category.no_results': 'Kategori bulunamadı',
        'category.cancel': 'İptal',
        'category.create': 'Oluştur',
        'category.update': 'Güncelle',
        'category.delete_confirm': '"{name}" silmek istediğinize emin misiniz?',
        'sillage_level.manage': 'Fark Edilirlik Seviyelerini Yönet',
        'sillage_level.manage.desc': 'Fark edilirlik seviyesi ekle, düzenle veya kaldır',
        'sillage_level.add': 'Seviye Ekle',
        'sillage_level.edit': 'Seviye Düzenle',
        'sillage_level.all': 'Tüm Seviyeler',
        'sillage_level.no_results': 'Seviye bulunamadı',
        'sillage_level.cancel': 'İptal',
        'sillage_level.create': 'Oluştur',
        'sillage_level.update': 'Güncelle',
        'sillage_level.delete_confirm': '"{name}" silmek istediğinize emin misiniz?',
        'field.sillage_levels': 'Fark Edilirlik Seviyeleri',
        'field.select_category': 'Kategori Seç',
    },
    ar: {
        'nav.perfumes': 'العطور',
        'nav.oils': 'الزيوت',
        'nav.manage': 'إدارة',
        'nav.dashboard': 'لوحة التحكم',
        'nav.repository': 'المستودع',
        'nav.documentation': 'الوثائق',
        'nav.nav_menu': 'قائمة التصفح',
        'user.settings': 'الإعدادات',
        'user.logout': 'تسجيل الخروج',
        'welcome.dashboard': 'لوحة التحكم',
        'welcome.login': 'تسجيل الدخول',
        'welcome.register': 'التسجيل',
        'welcome.getting_started': 'لنبدأ',
        'welcome.description': 'يحتوي Laravel على نظام بيئي غني بشكل لا يصدق. نقترح البدء بما يلي.',
        'welcome.read_docs': 'اقرأ',
        'welcome.documentation': 'الوثائق',
        'welcome.watch_tutorials': 'شاهد دروس الفيديو على',
        'welcome.laracasts': 'Laracasts',
        'welcome.deploy_now': 'انشر الآن',
        'perfume.title': 'العطور',
        'perfume.browse': 'العطور',
        'perfume.browse.desc': 'إدارة مخزون العطور الخاص بك',
        'perfume.add_btn': 'إضافة عطر',
        'perfume.search_placeholder': 'البحث بالاسم أو الكود أو العطر الأصلي...',
        'perfume.search_btn': 'بحث',
        'perfume.all_tab': 'الكل',
        'perfume.erkek_tab': 'Frequency Erkek',
        'perfume.kadin_tab': 'Frequency Kadın',
        'perfume.unisex_tab': 'Frequency Unisex',
        'perfume.niche_tab': 'نيش',
        'perfume.oil_tab': 'زيوت',
        'perfume.filter_all': 'الكل',
        'perfume.filter_summer': 'الصيف',
        'perfume.filter_autumn': 'الخريف',
        'perfume.filter_spring': 'الربيع',
        'perfume.filter_winter': 'الشتاء',
        'perfume.gender': 'الجنس',
        'perfume.family': 'العائلة',
        'perfume.shelf': 'الرف',
        'perfume.section': 'القسم',
        'perfume.clear_filters': 'مسح الفلاتر',
        'perfume.total_count': 'إجمالي العطور',
        'perfume.men_count': 'رجال',
        'perfume.women_count': 'نساء',
        'perfume.niche_count': 'نيش',
        'perfume.results_found': 'نتيجة تم العثور عليها',
        'perfume.sort_by': 'ترتيب حسب',
        'perfume.view_details': 'عرض التفاصيل',
        'perfume.frequency_erkek': 'Frequency Erkek',
        'perfume.frequency_kadin': 'Frequency Kadın',
        'perfume.per_page': 'في الصفحة',
        'perfume.manage': 'إدارة العطور',
        'perfume.manage.desc': 'إضافة أو تعديل أو إزالة العطور من المخزون',
        'perfume.add': 'إضافة عطر',
        'perfume.edit': 'تعديل العطر',
        'perfume.delete': 'حذف العطر',
        'perfume.fields': 'الحقول',
        'perfume.search': 'البحث عن عطر...',
        'perfume.all': 'جميع العطور',
        'perfume.total': 'إجمالي العطور',
        'perfume.no_results': 'لم يتم العثور على عطور',
        'perfume.cancel': 'إلغاء',
        'perfume.create': 'إنشاء',
        'perfume.update': 'تحديث',
        'perfume.delete_confirm': 'هل أنت متأكد من حذف "{name}" ({code})؟ لا يمكن التراجع عن هذا الإجراء.',
        'oil.title': 'الزيوت',
        'oil.manage': 'إدارة الزيوت',
        'oil.manage.desc': 'إضافة أو تعديل أو إزالة الزيوت من المخزون',
        'oil.add': 'إضافة زيت',
        'oil.edit': 'تعديل الزيت',
        'oil.delete': 'حذف الزيت',
        'oil.fields': 'الحقول',
        'oil.search': 'البحث عن زيت...',
        'oil.all': 'جميع الزيوت',
        'oil.total': 'إجمالي الزيوت',
        'oil.no_results': 'لم يتم العثور على زيوت',
        'oil.cancel': 'إلغاء',
        'oil.create': 'إنشاء',
        'oil.update': 'تحديث',
        'oil.delete_confirm': 'هل أنت متأكد من حذف "{name}" ({code})؟ لا يمكن التراجع عن هذا الإجراء.',
        'oil.browse': 'الزيوت',
        'oil.browse.desc': 'إدارة مخزون الزيوت الخاص بك',
        'oil.add_btn': 'إضافة زيت',
        'oil.search_placeholder': 'البحث بالاسم أو الكود أو العلامة التجارية أو المورد...',
        'oil.search_btn': 'بحث',
        'oil.all_tab': 'الكل',
        'oil.essential_tab': 'عطري',
        'oil.fragrance_tab': 'عطر',
        'oil.carrier_tab': 'ناقل',
        'oil.blend_tab': 'مزيج',
        'oil.category': 'الفئة',
        'oil.shelf': 'الرف',
        'oil.section': 'القسم',
        'oil.clear_filters': 'مسح الفلاتر',
        'oil.total_count': 'إجمالي الزيوت',
        'oil.essential_count': 'عطري',
        'oil.fragrance_count': 'عطر',
        'oil.carrier_count': 'ناقل',
        'oil.results_found': 'نتيجة تم العثور عليها',
        'oil.sort_by': 'ترتيب حسب',
        'oil.view_details': 'عرض التفاصيل',
        'oil.essential': 'عطري',
        'oil.fragrance': 'عطر',
        'oil.carrier': 'ناقل',
        'oil.pricing': 'التسعير',
        'field.name': 'الاسم',
        'field.code': 'الكود',
        'field.original_perfume': 'العطر الأصلي',
        'field.image': 'الصورة',
        'field.gender': 'الجنس',
        'field.family': 'العائلة',
        'field.shelf': 'الرف',
        'field.section': 'القسم',
        'field.season': 'الموسم',
        'field.notes': 'ملاحظات',
        'field.top_notes': 'النتجات العليا',
        'field.middle_notes': 'النتجات الوسطى',
        'field.base_notes': 'النتجات القاعدية',
        'field.warehouse': 'المستودع',
        'field.concentration': 'التركيز',
        'field.sillage': 'الانتشار',
        'field.price': 'السعر',
        'field.category': 'الفئة',
        'field.brand': 'العلامة التجارية',
        'field.volume': 'الحجم',
        'field.supplier': 'المورد',
        'field.type': 'النوع',
        'field.slug': 'الرابط',
        'field.fragrance_categories': 'فئات العطور',
        'field.seasons': 'الفصول',
        'field.image_choose': 'اختيار ملف',
        'field.image_keep': 'سيتم الاحتفاظ بالصورة الحالية',
        'field.image_none': 'لم يتم اختيار ملف',
        'gender.male': 'ذكر',
        'gender.female': 'أنثى',
        'gender.unisex': 'للجنسين',
        'season.summer': 'الصيف',
        'season.autumn': 'الخريف',
        'season.spring': 'الربيع',
        'season.winter': 'الشتاء',
        'season.manage': 'إدارة الفصول',
        'season.manage.desc': 'إضافة أو تعديل أو إزالة الفصول',
        'season.add': 'إضافة فصل',
        'season.edit': 'تعديل الفصل',
        'season.all': 'جميع الفصول',
        'season.no_results': 'لم يتم العثور على فصول',
        'season.cancel': 'إلغاء',
        'season.create': 'إنشاء',
        'season.update': 'تحديث',
        'season.delete_confirm': 'هل أنت متأكد من حذف "{name}"؟',
        'category.manage': 'إدارة فئات العطور',
        'category.manage.desc': 'إضافة أو تعديل أو إزالة فئات العطور',
        'category.add': 'إضافة فئة',
        'category.edit': 'تعديل الفئة',
        'category.all': 'جميع الفئات',
        'category.no_results': 'لم يتم العثور على فئات',
        'category.cancel': 'إلغاء',
        'category.create': 'إنشاء',
        'category.update': 'تحديث',
        'category.delete_confirm': 'هل أنت متأكد من حذف "{name}"؟',
        'sillage_level.manage': 'إدارة مستويات الانتشار',
        'sillage_level.manage.desc': 'إضافة أو تعديل أو إزالة مستويات الانتشار',
        'sillage_level.add': 'إضافة مستوى',
        'sillage_level.edit': 'تعديل المستوى',
        'sillage_level.all': 'جميع المستويات',
        'sillage_level.no_results': 'لم يتم العثور على مستويات',
        'sillage_level.cancel': 'إلغاء',
        'sillage_level.create': 'إنشاء',
        'sillage_level.update': 'تحديث',
        'sillage_level.delete_confirm': 'هل أنت متأكد من حذف "{name}"؟',
        'field.sillage_levels': 'مستويات الانتشار',
        'field.select_category': 'اختر فئة',
    },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [locale, setLocaleState] = useState<Locale>(() => {
        return (localStorage.getItem('locale') as Locale) || 'en';
    });

    const setLocale = (l: Locale) => {
        setLocaleState(l);
        localStorage.setItem('locale', l);
    };

    const dir = locale === 'ar' ? 'rtl' : 'ltr';

    const t = (key: string): string => {
        return translations[locale]?.[key] || translations.en?.[key] || key;
    };

    useEffect(() => {
        document.documentElement.dir = dir;
        document.documentElement.lang = locale;
    }, [locale, dir]);

    return (
        <LanguageContext.Provider value={{ locale, setLocale, t, dir }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
    return ctx;
}
